/* Special Surprise Pixel Dungeon, GPLv3 or later. */
package pd.actors.blobs;

import pd.Badges;
import pd.Dungeon;
import pd.actors.Actor;
import pd.actors.Char;
import pd.actors.hero.Hero;
import pd.effects.BlobEmitter;
import pd.effects.Speck;
import pd.messages.Messages;
import pd.utils.GLog;
import pd.messages.InlineText;

/** Nano cloud generated by the legacy soldier skin-four passive. */
public class NmGas extends Blob implements Hero.Doom {
	//SPSEXPD: inline Chinese text (generated from messages/actors/zh)
	static {
		InlineText.of(NmGas.class)
			.t("desc", "这里盘绕着纳米无人机云。除宿主外，所有吸入云雾的生物都会受到伤害。")
			.t("rankings_desc", "被纳米无人机云吞噬")
			.t("ondeath", "你被纳米无人机云吞噬了……");
	}


	@Override
	protected void evolve() {
		super.evolve();
		int damage = Dungeon.hero == null ? 0 : Dungeon.hero.spp;
		for (int cell = 0; cell < cur.length; cell++) {
			Char ch = cur[cell] > 0 ? Actor.findChar(cell) : null;
			if (ch != null && !ch.isImmune(getClass())) ch.damage(damage, this);
		}
	}

	@Override public void use(BlobEmitter emitter) {
		super.use(emitter);
		emitter.pour(Speck.factory(Speck.CONFUSION), 0.6f);
	}

	@Override public String tileDesc() { return Messages.get(this, "desc"); }

	@Override public void onDeath() {
		Badges.validateDeathFromGas();
		Dungeon.fail(this);
		GLog.n(Messages.get(this, "ondeath"));
	}
}
