package pd.atlas.interfaces;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/interfaces/banners/_atlas.json - do not edit by hand.
 *
 * atlas: interfaces/banners.png
 */
public final class BannersDict {

	private BannersDict() { }

	/** banner_000 */
	public static final IconEntry BANNER_000 = new IconEntry("interfaces/banners.png", new int[]{0, 0, 139, 100});
	/** banner_001 */
	public static final IconEntry BANNER_001 = new IconEntry("interfaces/banners.png", new int[]{139, 0, 139, 100});
	/** banner_002 */
	public static final IconEntry BANNER_002 = new IconEntry("interfaces/banners.png", new int[]{0, 100, 240, 57});
	/** banner_003 */
	public static final IconEntry BANNER_003 = new IconEntry("interfaces/banners.png", new int[]{240, 100, 240, 57});
	/** banner_004 */
	public static final IconEntry BANNER_004 = new IconEntry("interfaces/banners.png", new int[]{0, 157, 127, 68});
	/** banner_005 */
	public static final IconEntry BANNER_005 = new IconEntry("interfaces/banners.png", new int[]{128, 157, 128, 35});
}
