package pd.atlas.interfaces;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/interfaces/hero_icons/_atlas.json - do not edit by hand.
 *
 * atlas: interfaces/hero_icons.png
 */
public final class HeroIconsDict {

	private HeroIconsDict() { }

	/** hicon_000 */
	public static final IconEntry HICON_000 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 0, 16, 16});
	/** hicon_001 */
	public static final IconEntry HICON_001 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 0, 16, 16});
	/** hicon_002 */
	public static final IconEntry HICON_002 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 0, 16, 16});
	/** hicon_003 */
	public static final IconEntry HICON_003 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 0, 16, 16});
	/** hicon_004 */
	public static final IconEntry HICON_004 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 0, 16, 16});
	/** hicon_005 */
	public static final IconEntry HICON_005 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 0, 16, 16});
	/** hicon_006 */
	public static final IconEntry HICON_006 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 0, 16, 16});
	/** hicon_007 */
	public static final IconEntry HICON_007 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 0, 16, 16});
	/** hicon_008 */
	public static final IconEntry HICON_008 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 16, 16, 16});
	/** hicon_009 */
	public static final IconEntry HICON_009 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 16, 16, 16});
	/** hicon_010 */
	public static final IconEntry HICON_010 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 16, 16, 16});
	/** hicon_011 */
	public static final IconEntry HICON_011 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 16, 16, 16});
	/** hicon_012 */
	public static final IconEntry HICON_012 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 16, 16, 16});
	/** hicon_013 */
	public static final IconEntry HICON_013 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 16, 16, 16});
	/** hicon_014 */
	public static final IconEntry HICON_014 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 16, 16, 16});
	/** hicon_015 */
	public static final IconEntry HICON_015 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 16, 16, 16});
	/** hicon_016 */
	public static final IconEntry HICON_016 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 32, 16, 16});
	/** hicon_017 */
	public static final IconEntry HICON_017 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 32, 16, 16});
	/** hicon_018 */
	public static final IconEntry HICON_018 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 32, 16, 16});
	/** hicon_019 */
	public static final IconEntry HICON_019 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 32, 16, 16});
	/** hicon_020 */
	public static final IconEntry HICON_020 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 32, 16, 16});
	/** hicon_021 */
	public static final IconEntry HICON_021 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 32, 16, 16});
	/** hicon_022 */
	public static final IconEntry HICON_022 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 32, 16, 16});
	/** hicon_023 */
	public static final IconEntry HICON_023 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 32, 16, 16});
	/** hicon_024 */
	public static final IconEntry HICON_024 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 48, 16, 16});
	/** hicon_025 */
	public static final IconEntry HICON_025 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 48, 16, 16});
	/** hicon_026 */
	public static final IconEntry HICON_026 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 48, 16, 16});
	/** hicon_027 */
	public static final IconEntry HICON_027 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 48, 16, 16});
	/** hicon_028 */
	public static final IconEntry HICON_028 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 48, 16, 16});
	/** hicon_029 */
	public static final IconEntry HICON_029 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 48, 16, 16});
	/** hicon_030 */
	public static final IconEntry HICON_030 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 48, 16, 16});
	/** hicon_031 */
	public static final IconEntry HICON_031 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 48, 16, 16});
	/** hicon_032 */
	public static final IconEntry HICON_032 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 64, 16, 16});
	/** hicon_033 */
	public static final IconEntry HICON_033 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 64, 16, 16});
	/** hicon_034 */
	public static final IconEntry HICON_034 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 64, 16, 16});
	/** hicon_035 */
	public static final IconEntry HICON_035 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 64, 16, 16});
	/** hicon_036 */
	public static final IconEntry HICON_036 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 64, 16, 16});
	/** hicon_037 */
	public static final IconEntry HICON_037 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 64, 16, 16});
	/** hicon_038 */
	public static final IconEntry HICON_038 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 64, 16, 16});
	/** hicon_039 */
	public static final IconEntry HICON_039 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 64, 16, 16});
	/** hicon_040 */
	public static final IconEntry HICON_040 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 80, 16, 16});
	/** hicon_041 */
	public static final IconEntry HICON_041 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 80, 16, 16});
	/** hicon_042 */
	public static final IconEntry HICON_042 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 80, 16, 16});
	/** hicon_043 */
	public static final IconEntry HICON_043 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 80, 16, 16});
	/** hicon_044 */
	public static final IconEntry HICON_044 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 80, 16, 16});
	/** hicon_045 */
	public static final IconEntry HICON_045 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 80, 16, 16});
	/** hicon_046 */
	public static final IconEntry HICON_046 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 80, 16, 16});
	/** hicon_047 */
	public static final IconEntry HICON_047 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 80, 16, 16});
	/** hicon_048 */
	public static final IconEntry HICON_048 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 96, 16, 16});
	/** hicon_049 */
	public static final IconEntry HICON_049 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 96, 16, 16});
	/** hicon_050 */
	public static final IconEntry HICON_050 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 96, 16, 16});
	/** hicon_051 */
	public static final IconEntry HICON_051 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 96, 16, 16});
	/** hicon_052 */
	public static final IconEntry HICON_052 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 96, 16, 16});
	/** hicon_053 */
	public static final IconEntry HICON_053 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 96, 16, 16});
	/** hicon_054 */
	public static final IconEntry HICON_054 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 96, 16, 16});
	/** hicon_055 */
	public static final IconEntry HICON_055 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 96, 16, 16});
	/** hicon_056 */
	public static final IconEntry HICON_056 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 112, 16, 16});
	/** hicon_057 */
	public static final IconEntry HICON_057 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 112, 16, 16});
	/** hicon_058 */
	public static final IconEntry HICON_058 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 112, 16, 16});
	/** hicon_059 */
	public static final IconEntry HICON_059 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 112, 16, 16});
	/** hicon_060 */
	public static final IconEntry HICON_060 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 112, 16, 16});
	/** hicon_061 */
	public static final IconEntry HICON_061 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 112, 16, 16});
	/** hicon_062 */
	public static final IconEntry HICON_062 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 112, 16, 16});
	/** hicon_063 */
	public static final IconEntry HICON_063 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 112, 16, 16});
	/** hicon_064 */
	public static final IconEntry HICON_064 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 128, 16, 16});
	/** hicon_065 */
	public static final IconEntry HICON_065 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 128, 16, 16});
	/** hicon_066 */
	public static final IconEntry HICON_066 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 128, 16, 16});
	/** hicon_067 */
	public static final IconEntry HICON_067 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 128, 16, 16});
	/** hicon_068 */
	public static final IconEntry HICON_068 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 128, 16, 16});
	/** hicon_069 */
	public static final IconEntry HICON_069 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 128, 16, 16});
	/** hicon_070 */
	public static final IconEntry HICON_070 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 128, 16, 16});
	/** hicon_071 */
	public static final IconEntry HICON_071 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 128, 16, 16});
	/** hicon_072 */
	public static final IconEntry HICON_072 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 144, 16, 16});
	/** hicon_073 */
	public static final IconEntry HICON_073 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 144, 16, 16});
	/** hicon_074 */
	public static final IconEntry HICON_074 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 144, 16, 16});
	/** hicon_075 */
	public static final IconEntry HICON_075 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 144, 16, 16});
	/** hicon_076 */
	public static final IconEntry HICON_076 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 144, 16, 16});
	/** hicon_077 */
	public static final IconEntry HICON_077 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 144, 16, 16});
	/** hicon_078 */
	public static final IconEntry HICON_078 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 144, 16, 16});
	/** hicon_079 */
	public static final IconEntry HICON_079 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 144, 16, 16});
	/** hicon_080 */
	public static final IconEntry HICON_080 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 160, 16, 16});
	/** hicon_081 */
	public static final IconEntry HICON_081 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 160, 16, 16});
	/** hicon_082 */
	public static final IconEntry HICON_082 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 160, 16, 16});
	/** hicon_083 */
	public static final IconEntry HICON_083 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 160, 16, 16});
	/** hicon_084 */
	public static final IconEntry HICON_084 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 160, 16, 16});
	/** hicon_085 */
	public static final IconEntry HICON_085 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 160, 16, 16});
	/** hicon_086 */
	public static final IconEntry HICON_086 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 160, 16, 16});
	/** hicon_087 */
	public static final IconEntry HICON_087 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 160, 16, 16});
	/** hicon_088 */
	public static final IconEntry HICON_088 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 176, 16, 16});
	/** hicon_089 */
	public static final IconEntry HICON_089 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 176, 16, 16});
	/** hicon_090 */
	public static final IconEntry HICON_090 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 176, 16, 16});
	/** hicon_091 */
	public static final IconEntry HICON_091 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 176, 16, 16});
	/** hicon_092 */
	public static final IconEntry HICON_092 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 176, 16, 16});
	/** hicon_093 */
	public static final IconEntry HICON_093 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 176, 16, 16});
	/** hicon_094 */
	public static final IconEntry HICON_094 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 176, 16, 16});
	/** hicon_095 */
	public static final IconEntry HICON_095 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 176, 16, 16});
	/** hicon_096 */
	public static final IconEntry HICON_096 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 192, 16, 16});
	/** hicon_097 */
	public static final IconEntry HICON_097 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 192, 16, 16});
	/** hicon_098 */
	public static final IconEntry HICON_098 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 192, 16, 16});
	/** hicon_099 */
	public static final IconEntry HICON_099 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 192, 16, 16});
	/** hicon_100 */
	public static final IconEntry HICON_100 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 192, 16, 16});
	/** hicon_101 */
	public static final IconEntry HICON_101 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 192, 16, 16});
	/** hicon_102 */
	public static final IconEntry HICON_102 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 192, 16, 16});
	/** hicon_103 */
	public static final IconEntry HICON_103 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 192, 16, 16});
	/** hicon_104 */
	public static final IconEntry HICON_104 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 208, 16, 16});
	/** hicon_105 */
	public static final IconEntry HICON_105 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 208, 16, 16});
	/** hicon_106 */
	public static final IconEntry HICON_106 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 208, 16, 16});
	/** hicon_107 */
	public static final IconEntry HICON_107 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 208, 16, 16});
	/** hicon_108 */
	public static final IconEntry HICON_108 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 208, 16, 16});
	/** hicon_109 */
	public static final IconEntry HICON_109 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 208, 16, 16});
	/** hicon_110 */
	public static final IconEntry HICON_110 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 208, 16, 16});
	/** hicon_111 */
	public static final IconEntry HICON_111 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 208, 16, 16});
	/** hicon_112 */
	public static final IconEntry HICON_112 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 224, 16, 16});
	/** hicon_113 */
	public static final IconEntry HICON_113 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 224, 16, 16});
	/** hicon_114 */
	public static final IconEntry HICON_114 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 224, 16, 16});
	/** hicon_115 */
	public static final IconEntry HICON_115 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 224, 16, 16});
	/** hicon_116 */
	public static final IconEntry HICON_116 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 224, 16, 16});
	/** hicon_117 */
	public static final IconEntry HICON_117 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 224, 16, 16});
	/** hicon_118 */
	public static final IconEntry HICON_118 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 224, 16, 16});
	/** hicon_119 */
	public static final IconEntry HICON_119 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 224, 16, 16});
	/** hicon_120 */
	public static final IconEntry HICON_120 = new IconEntry("interfaces/hero_icons.png", new int[]{0, 240, 16, 16});
	/** hicon_121 */
	public static final IconEntry HICON_121 = new IconEntry("interfaces/hero_icons.png", new int[]{16, 240, 16, 16});
	/** hicon_122 */
	public static final IconEntry HICON_122 = new IconEntry("interfaces/hero_icons.png", new int[]{32, 240, 16, 16});
	/** hicon_123 */
	public static final IconEntry HICON_123 = new IconEntry("interfaces/hero_icons.png", new int[]{48, 240, 16, 16});
	/** hicon_124 */
	public static final IconEntry HICON_124 = new IconEntry("interfaces/hero_icons.png", new int[]{64, 240, 16, 16});
	/** hicon_125 */
	public static final IconEntry HICON_125 = new IconEntry("interfaces/hero_icons.png", new int[]{80, 240, 16, 16});
	/** hicon_126 */
	public static final IconEntry HICON_126 = new IconEntry("interfaces/hero_icons.png", new int[]{96, 240, 16, 16});
	/** hicon_127 */
	public static final IconEntry HICON_127 = new IconEntry("interfaces/hero_icons.png", new int[]{112, 240, 16, 16});
}
