/* Special Surprise Pixel Dungeon, GPLv3 or later. */
package com.shatteredpixel.shatteredpixeldungeon.actors.blobs;

import com.shatteredpixel.shatteredpixeldungeon.Badges;
import com.shatteredpixel.shatteredpixeldungeon.Dungeon;
import com.shatteredpixel.shatteredpixeldungeon.actors.Actor;
import com.shatteredpixel.shatteredpixeldungeon.actors.Char;
import com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero;
import com.shatteredpixel.shatteredpixeldungeon.effects.BlobEmitter;
import com.shatteredpixel.shatteredpixeldungeon.effects.Speck;
import com.shatteredpixel.shatteredpixeldungeon.messages.Messages;
import com.shatteredpixel.shatteredpixeldungeon.utils.GLog;

/** Nano cloud generated by the legacy soldier skin-four passive. */
public class NmGas extends Blob implements Hero.Doom {

	@Override
	protected void evolve() {
		super.evolve();
		int damage = Dungeon.hero == null ? 0 : Dungeon.hero.spp;
		for (int cell = 0; cell < cur.length; cell++) {
			Char ch = cur[cell] > 0 ? Actor.findChar(cell) : null;
			if (ch != null && !ch.isImmune(getClass())) ch.damage(damage, this);
		}
	}

	@Override public void use(BlobEmitter emitter) {
		super.use(emitter);
		emitter.pour(Speck.factory(Speck.CONFUSION), 0.6f);
	}

	@Override public String tileDesc() { return Messages.get(this, "desc"); }

	@Override public void onDeath() {
		Badges.validateDeathFromGas();
		Dungeon.fail(this);
		GLog.n(Messages.get(this, "ondeath"));
	}
}
