package pd.atlas.environment;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/environment/weak_floor/_atlas.json - do not edit by hand.
 *
 * atlas: environment/custom_tiles/weak_floor.png
 */
public final class WeakFloorDict {

	private WeakFloorDict() { }

	/** tile_000 */
	public static final IconEntry TILE_000 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{0, 0, 16, 16}, 4888);
	/** tile_001 */
	public static final IconEntry TILE_001 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{16, 0, 16, 16}, 4889);
	/** tile_002 */
	public static final IconEntry TILE_002 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{32, 0, 16, 16}, 4890);
	/** tile_003 */
	public static final IconEntry TILE_003 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{48, 0, 16, 16}, 4891);
	/** tile_004 */
	public static final IconEntry TILE_004 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{64, 0, 16, 16}, 4892);
	/** tile_005 */
	public static final IconEntry TILE_005 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{80, 0, 16, 16}, 4893);
	/** tile_006 */
	public static final IconEntry TILE_006 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{96, 0, 16, 16}, 4894);
	/** tile_007 */
	public static final IconEntry TILE_007 = new IconEntry("environment/custom_tiles/weak_floor.png", new int[]{112, 0, 16, 16}, 4895);
}
