package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/consum/scroll_amulet/scroll_empty/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/consum/scroll_amulet/scroll_empty.png
 */
public final class ConsumScrollAmuletScrollEmptyDict {

	private ConsumScrollAmuletScrollEmptyDict() { }

	/** SCROLL_EMPTY */
	public static final IconEntry SCROLL_EMPTY = new IconEntry("sprites/items/consum/scroll_amulet/scroll_empty.png", new int[]{0, 0, 16, 16}, 7134);
}
