package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/consum/useful/useful/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/consum/useful/useful.png
 */
public final class ConsumUsefulUsefulDict {

	private ConsumUsefulUsefulDict() { }

	/** foods/PET_FOOD */
	public static final IconEntry FOODS_PET_FOOD = new IconEntry("sprites/items/consum/useful/useful.png", new int[]{64, 16, 16, 16});
}
