package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/consum/scroll_amulet/scroll/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/consum/scroll_amulet/scroll.png
 */
public final class ConsumScrollAmuletScrollDict {

	private ConsumScrollAmuletScrollDict() { }

	/** SCROLL_ENCHANT_LEGACY */
	public static final IconEntry SCROLL_ENCHANT_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{1, 1, 15, 14});
	/** EXOTIC_SOWILO_LEGACY */
	public static final IconEntry EXOTIC_SOWILO_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{17, 1, 15, 14});
	/** EXOTIC_LAGUZ_LEGACY */
	public static final IconEntry EXOTIC_LAGUZ_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{33, 1, 15, 14});
	/** EXOTIC_YNGVI_LEGACY */
	public static final IconEntry EXOTIC_YNGVI_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{49, 1, 15, 14});
	/** SCROLL_MYSTENRG_LEGACY */
	public static final IconEntry SCROLL_MYSTENRG_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{65, 1, 15, 14});
	/** EXOTIC_RAIDO_LEGACY */
	public static final IconEntry EXOTIC_RAIDO_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{81, 1, 15, 14});
	/** SCROLL_SIREN_LEGACY */
	public static final IconEntry SCROLL_SIREN_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{97, 1, 15, 14});
	/** SCROLL_FORESIGHT_LEGACY */
	public static final IconEntry SCROLL_FORESIGHT_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{113, 1, 15, 14});
	/** SCROLL_CHALLENGE_LEGACY */
	public static final IconEntry SCROLL_CHALLENGE_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{129, 1, 15, 14});
	/** EXOTIC_BERKANAN_LEGACY */
	public static final IconEntry EXOTIC_BERKANAN_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{145, 1, 15, 14});
	/** SCROLL_DREAD_LEGACY */
	public static final IconEntry SCROLL_DREAD_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{161, 1, 15, 14});
	/** SCROLL_METAMORPH_LEGACY */
	public static final IconEntry SCROLL_METAMORPH_LEGACY = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{177, 1, 15, 14});
	/** SPS_SCROLL_A */
	public static final IconEntry SPS_SCROLL_A = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{193, 1, 15, 14});
	/** SPS_SCROLL_B */
	public static final IconEntry SPS_SCROLL_B = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{209, 1, 15, 14});
	/** SPS_SCROLL_C */
	public static final IconEntry SPS_SCROLL_C = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{225, 1, 15, 14});
	/** SCROLL_ENCHANT#0 */
	public static final IconEntry SCROLL_ENCHANT_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{0, 16, 15, 14});
	/** EXOTIC_SOWILO#0 */
	public static final IconEntry EXOTIC_SOWILO_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{16, 16, 15, 14});
	/** EXOTIC_LAGUZ#0 */
	public static final IconEntry EXOTIC_LAGUZ_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{32, 16, 15, 14});
	/** EXOTIC_YNGVI#0 */
	public static final IconEntry EXOTIC_YNGVI_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{48, 16, 15, 14});
	/** SCROLL_MYSTENRG#0 */
	public static final IconEntry SCROLL_MYSTENRG_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{64, 16, 15, 14});
	/** EXOTIC_RAIDO#0 */
	public static final IconEntry EXOTIC_RAIDO_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{80, 16, 15, 14});
	/** SCROLL_SIREN#0 */
	public static final IconEntry SCROLL_SIREN_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{96, 16, 15, 14});
	/** SCROLL_FORESIGHT#0 */
	public static final IconEntry SCROLL_FORESIGHT_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{112, 16, 15, 14});
	/** SCROLL_CHALLENGE#0 */
	public static final IconEntry SCROLL_CHALLENGE_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{128, 16, 15, 14});
	/** EXOTIC_BERKANAN#0 */
	public static final IconEntry EXOTIC_BERKANAN_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{144, 16, 15, 14});
	/** SCROLL_DREAD#0 */
	public static final IconEntry SCROLL_DREAD_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{160, 16, 15, 14});
	/** SCROLL_METAMORPH#0 */
	public static final IconEntry SCROLL_METAMORPH_0 = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{176, 16, 15, 14});
	/** SCROLL_OF_PRECISION */
	public static final IconEntry SCROLL_OF_PRECISION = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{193, 17, 15, 14});
	/** SCROLL_OF_PROTECTION */
	public static final IconEntry SCROLL_OF_PROTECTION = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{209, 17, 15, 14});
	/** SCROLL_OF_MAGIC */
	public static final IconEntry SCROLL_OF_MAGIC = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{225, 17, 15, 14});
	/** ENCHANT_CUBE */
	public static final IconEntry ENCHANT_CUBE = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{210, 50, 12, 13});
	/** ARCANE_RESIN */
	public static final IconEntry ARCANE_RESIN = new IconEntry("sprites/items/consum/scroll_amulet/scroll.png", new int[]{226, 51, 12, 11});
}
