package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/consum/scroll_amulet/crystal/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/consum/scroll_amulet/crystal.png
 */
public final class ConsumScrollAmuletCrystalDict {

	private ConsumScrollAmuletCrystalDict() { }

	/** misc/ALCHEMIZE */
	public static final IconEntry MISC_ALCHEMIZE = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{96, 0, 12, 12});
	/** misc/CURSE_INFUSE */
	public static final IconEntry MISC_CURSE_INFUSE = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{64, 0, 10, 16});
	/** misc/MAGIC_INFUSE */
	public static final IconEntry MISC_MAGIC_INFUSE = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{80, 0, 10, 14});
	/** misc/PHASE_SHIFT */
	public static final IconEntry MISC_PHASE_SHIFT = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{16, 0, 12, 10});
	/** misc/RECLAIM_TRAP */
	public static final IconEntry MISC_RECLAIM_TRAP = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{128, 0, 14, 11});
	/** misc/RECYCLE */
	public static final IconEntry MISC_RECYCLE = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{112, 0, 12, 13});
	/** misc/RETURN_BEACON */
	public static final IconEntry MISC_RETURN_BEACON = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{144, 0, 8, 16});
	/** misc/TELE_GRAB */
	public static final IconEntry MISC_TELE_GRAB = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{32, 0, 10, 10});
	/** misc/UNSTABLE_SPELL */
	public static final IconEntry MISC_UNSTABLE_SPELL = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{48, 0, 12, 13});
	/** misc/WILD_ENERGY */
	public static final IconEntry MISC_WILD_ENERGY = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{0, 0, 6, 15});
	/** stones/summon_ele */
	public static final IconEntry STONES_SUMMON_ELE = new IconEntry("sprites/items/consum/scroll_amulet/crystal.png", new int[]{160, 0, 8, 16, 176, 0, 8, 16, 192, 0, 8, 16, 208, 0, 8, 16, 224, 0, 8, 16});
}
