package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/consum/useful/process_enhance/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/consum/useful/process_enhance.png
 */
public final class ConsumUsefulProcessEnhanceDict {

	private ConsumUsefulProcessEnhanceDict() { }

	/** documents/LEGACY_BRAVE_BOOK */
	public static final IconEntry DOCUMENTS_LEGACY_BRAVE_BOOK = new IconEntry("sprites/items/consum/useful/process_enhance.png", new int[]{16, 16, 16, 16});
	/** misc/CROWN */
	public static final IconEntry MISC_CROWN = new IconEntry("sprites/items/consum/useful/process_enhance.png", new int[]{0, 16, 13, 7});
	/** misc/KIT */
	public static final IconEntry MISC_KIT = new IconEntry("sprites/items/consum/useful/process_enhance.png", new int[]{32, 0, 16, 15});
	/** misc/MASK */
	public static final IconEntry MISC_MASK = new IconEntry("sprites/items/consum/useful/process_enhance.png", new int[]{0, 0, 11, 9});
	/** misc/MASTERY */
	public static final IconEntry MISC_MASTERY = new IconEntry("sprites/items/consum/useful/process_enhance.png", new int[]{17, 0, 13, 16});
}
