package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/equipment/jewellery/artifact/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/equipment/jewellery/artifact.png
 */
public final class EquipmentJewelleryArtifactDict {

	private EquipmentJewelleryArtifactDict() { }

	/** artifacts/ARTIFACT_BEACON */
	public static final IconEntry ARTIFACTS_ARTIFACT_BEACON = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{48, 16, 16, 16});
	/** artifacts/ARTIFACT_ICE_EYE */
	public static final IconEntry ARTIFACTS_ARTIFACT_ICE_EYE = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{96, 16, 16, 16});
	/** artifacts/ARTIFACT_KEY */
	public static final IconEntry ARTIFACTS_ARTIFACT_KEY = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{308, 0, 8, 16});
	/** artifacts/horn */
	public static final IconEntry ARTIFACTS_HORN = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{160, 0, 15, 15});
	/** artifacts/NOOMLIN_CROWN */
	public static final IconEntry ARTIFACTS_NOOMLIN_CROWN = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{96, 48, 16, 16});
	/** artifacts/SPS_GLASS_TOTEM */
	public static final IconEntry ARTIFACTS_SPS_GLASS_TOTEM = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{112, 16, 16, 16});
	/** misc/CURSE_PHONE */
	public static final IconEntry MISC_CURSE_PHONE = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{0, 48, 16, 16});
	/** misc/FOUR_CLOVER */
	public static final IconEntry MISC_FOUR_CLOVER = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{64, 48, 16, 16});
	/** misc/LEGACY_ALIEN_BAG */
	public static final IconEntry MISC_LEGACY_ALIEN_BAG = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{128, 16, 16, 16});
	/** misc/LEGACY_TIME_OCLOCK */
	public static final IconEntry MISC_LEGACY_TIME_OCLOCK = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{64, 0, 16, 16});
	/** misc/LING_HEART */
	public static final IconEntry MISC_LING_HEART = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{16, 48, 16, 16});
	/** misc/SPS_ROBOT_HEART */
	public static final IconEntry MISC_SPS_ROBOT_HEART = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{80, 16, 16, 16});
	/** potions/AUTO_POTION */
	public static final IconEntry POTIONS_AUTO_POTION = new IconEntry("sprites/items/equipment/jewellery/artifact.png", new int[]{80, 48, 16, 16});
}
