package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/equipment/equip/weapon/unique_weapon/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/equipment/equip/weapon/unique_weapon.png
 */
public final class EquipmentEquipWeaponUniqueWeaponDict {

	private EquipmentEquipWeaponUniqueWeaponDict() { }

	/** misc/LEGACY_BOOMERANG */
	public static final IconEntry MISC_LEGACY_BOOMERANG = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{0, 80, 16, 16});
	/** misc/LEGACY_BULLET */
	public static final IconEntry MISC_LEGACY_BULLET = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{112, 80, 16, 16});
	/** misc/MANY_KNIVE */
	public static final IconEntry MISC_MANY_KNIVE = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{48, 80, 16, 16});
	/** misc/SPS_ELE_KATANA */
	public static final IconEntry MISC_SPS_ELE_KATANA = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{80, 0, 16, 16});
	/** wands/WAND_FLOW */
	public static final IconEntry WANDS_WAND_FLOW = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{144, 80, 16, 16});
	/** wands/WAND_SPS_MAGIC_MISSILE */
	public static final IconEntry WANDS_WAND_SPS_MAGIC_MISSILE = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{96, 80, 16, 16});
	/** weapons/LEGACY_DIAMOND_PICKAXE */
	public static final IconEntry WEAPONS_LEGACY_DIAMOND_PICKAXE = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{32, 16, 16, 16});
	/** weapons/LEGACY_HOLY_MACE */
	public static final IconEntry WEAPONS_LEGACY_HOLY_MACE = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{0, 16, 16, 16});
	/** weapons/LEGACY_LINK_SWORD */
	public static final IconEntry WEAPONS_LEGACY_LINK_SWORD = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{0, 0, 16, 16});
	/** weapons/LEGACY_SOLDIER_AMMO */
	public static final IconEntry WEAPONS_LEGACY_SOLDIER_AMMO = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{128, 80, 16, 16});
	/** weapons/SPIRIT_BOW */
	public static final IconEntry WEAPONS_SPIRIT_BOW = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{16, 80, 16, 16});
	/** weapons/SPS_DEMON_BLADE */
	public static final IconEntry WEAPONS_SPS_DEMON_BLADE = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{80, 80, 16, 16});
	/** weapons/SPS_ELF_BOW */
	public static final IconEntry WEAPONS_SPS_ELF_BOW = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{64, 80, 16, 16});
	/** weapons/SPS_TAURCEN_BOW */
	public static final IconEntry WEAPONS_SPS_TAURCEN_BOW = new IconEntry("sprites/items/equipment/equip/weapon/unique_weapon.png", new int[]{32, 80, 16, 16});
}
