package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/ground/functional_falling/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/ground/functional_falling.png
 */
public final class GroundFunctionalFallingDict {

	private GroundFunctionalFallingDict() { }

	/** dewdrop#0 */
	public static final IconEntry DEWDROP_0 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{3, 3, 10, 10});
	/** dewdrop#1 */
	public static final IconEntry DEWDROP_1 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{19, 3, 10, 10});
	/** dewdrop#2 */
	public static final IconEntry DEWDROP_2 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{35, 3, 10, 13});
	/** dewdrop#3 */
	public static final IconEntry DEWDROP_3 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{51, 3, 10, 10});
	/** dewdrop#4 */
	public static final IconEntry DEWDROP_4 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{67, 3, 10, 10});
	/** PETAL#0 */
	public static final IconEntry PETAL_0 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{4, 20, 8, 8});
	/** SANDBAG#0 */
	public static final IconEntry SANDBAG_0 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{19, 19, 10, 10});
	/** SPIRIT_ARROW#0 */
	public static final IconEntry SPIRIT_ARROW_0 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{35, 19, 11, 11});
	/** TENGU_BOMB#0 */
	public static final IconEntry TENGU_BOMB_0 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{51, 19, 10, 10});
	/** TENGU_SHOCKER#0 */
	public static final IconEntry TENGU_SHOCKER_0 = new IconEntry("sprites/items/ground/functional_falling.png", new int[]{67, 19, 10, 10});
}
