package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/specific/place_holder/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/specific/place_holder.png
 */
public final class SpecificPlaceHolderDict {

	private SpecificPlaceHolderDict() { }

	/** SPS_PH_ERROR */
	public static final IconEntry SPS_PH_ERROR = new IconEntry("sprites/items/specific/place_holder.png", new int[]{0, 4, 16, 7});
	/** SPS_PH_WEAPON */
	public static final IconEntry SPS_PH_WEAPON = new IconEntry("sprites/items/specific/place_holder.png", new int[]{17, 1, 14, 14});
	/** SPS_PH_ARMOR */
	public static final IconEntry SPS_PH_ARMOR = new IconEntry("sprites/items/specific/place_holder.png", new int[]{33, 1, 14, 12});
	/** WAND_HOLDER#0 */
	public static final IconEntry WAND_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{49, 1, 14, 14});
	/** ARTIFACT_HOLDER#0 */
	public static final IconEntry ARTIFACT_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{64, 0, 15, 15});
	/** TRINKET_HOLDER#0 */
	public static final IconEntry TRINKET_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{80, 2, 16, 11});
	/** SPS_PH_FOOD */
	public static final IconEntry SPS_PH_FOOD = new IconEntry("sprites/items/specific/place_holder.png", new int[]{97, 3, 14, 11});
	/** SPS_UI_ICON_CATALOG */
	public static final IconEntry SPS_UI_ICON_CATALOG = new IconEntry("sprites/items/specific/place_holder.png", new int[]{113, 1, 14, 14});
	/** SCROLL_HOLDER#0 */
	public static final IconEntry SCROLL_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{128, 1, 15, 14});
	/** POTION_HOLDER#0 */
	public static final IconEntry POTION_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{146, 1, 12, 14});
	/** MOB_HOLDER#0 */
	public static final IconEntry MOB_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{208, 1, 15, 14});
	/** SPS_UI_ICON_A */
	public static final IconEntry SPS_UI_ICON_A = new IconEntry("sprites/items/specific/place_holder.png", new int[]{227, 2, 11, 12});
	/** SPS_UI_ICON_B */
	public static final IconEntry SPS_UI_ICON_B = new IconEntry("sprites/items/specific/place_holder.png", new int[]{242, 4, 13, 10});
	/** SOMETHING#0 */
	public static final IconEntry SOMETHING_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{4, 18, 8, 13});
	/** SPS_PH_WEAPON_BAD */
	public static final IconEntry SPS_PH_WEAPON_BAD = new IconEntry("sprites/items/specific/place_holder.png", new int[]{17, 17, 14, 14});
	/** SPS_PH_ARMOR_BAD */
	public static final IconEntry SPS_PH_ARMOR_BAD = new IconEntry("sprites/items/specific/place_holder.png", new int[]{33, 17, 14, 12});
	/** SPS_PH_WAND_BAD */
	public static final IconEntry SPS_PH_WAND_BAD = new IconEntry("sprites/items/specific/place_holder.png", new int[]{49, 17, 14, 14});
	/** RING_HOLDER#0 */
	public static final IconEntry RING_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{68, 19, 8, 10});
	/** FOOD_HOLDER#0 */
	public static final IconEntry FOOD_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{96, 18, 15, 11});
	/** STONE_HOLDER#0 */
	public static final IconEntry STONE_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{129, 18, 14, 12});
	/** SEED_HOLDER#0 */
	public static final IconEntry SEED_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{147, 19, 10, 10});
	/** SPS_UI_ICON_C */
	public static final IconEntry SPS_UI_ICON_C = new IconEntry("sprites/items/specific/place_holder.png", new int[]{209, 18, 14, 11});
	/** SPS_UI_ICON_D */
	public static final IconEntry SPS_UI_ICON_D = new IconEntry("sprites/items/specific/place_holder.png", new int[]{226, 17, 12, 14});
	/** SPS_UI_ICON_E */
	public static final IconEntry SPS_UI_ICON_E = new IconEntry("sprites/items/specific/place_holder.png", new int[]{241, 17, 13, 14});
	/** SPS_PH_LOG */
	public static final IconEntry SPS_PH_LOG = new IconEntry("sprites/items/specific/place_holder.png", new int[]{4, 36, 8, 9});
	/** SPS_PH_WEAPON_TEST */
	public static final IconEntry SPS_PH_WEAPON_TEST = new IconEntry("sprites/items/specific/place_holder.png", new int[]{17, 33, 14, 14});
	/** SPS_PH_ARMOR_TEST */
	public static final IconEntry SPS_PH_ARMOR_TEST = new IconEntry("sprites/items/specific/place_holder.png", new int[]{33, 33, 14, 12});
	/** SPS_PH_WAND_TEST */
	public static final IconEntry SPS_PH_WAND_TEST = new IconEntry("sprites/items/specific/place_holder.png", new int[]{49, 33, 14, 14});
	/** SPS_PH_TRINKET */
	public static final IconEntry SPS_PH_TRINKET = new IconEntry("sprites/items/specific/place_holder.png", new int[]{65, 35, 14, 11});
	/** SPS_PH_ALCHEMY */
	public static final IconEntry SPS_PH_ALCHEMY = new IconEntry("sprites/items/specific/place_holder.png", new int[]{99, 35, 10, 10});
	/** ELIXIR_HOLDER#0 */
	public static final IconEntry ELIXIR_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{130, 33, 12, 14});
	/** SPELL_HOLDER#0 */
	public static final IconEntry SPELL_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{148, 32, 8, 16});
	/** DOCUMENT_HOLDER#0 */
	public static final IconEntry DOCUMENT_HOLDER_0 = new IconEntry("sprites/items/specific/place_holder.png", new int[]{3, 50, 10, 11});
	/** SPS_PH_WEAPON_SPARE */
	public static final IconEntry SPS_PH_WEAPON_SPARE = new IconEntry("sprites/items/specific/place_holder.png", new int[]{17, 49, 14, 14});
	/** SPS_PH_ARMOR_SPARE */
	public static final IconEntry SPS_PH_ARMOR_SPARE = new IconEntry("sprites/items/specific/place_holder.png", new int[]{33, 50, 14, 12});
	/** SPS_PH_WAND_SPARE */
	public static final IconEntry SPS_PH_WAND_SPARE = new IconEntry("sprites/items/specific/place_holder.png", new int[]{49, 49, 14, 14});
	/** SPS_PH_BADGE */
	public static final IconEntry SPS_PH_BADGE = new IconEntry("sprites/items/specific/place_holder.png", new int[]{65, 49, 14, 14});
	/** SPS_GOLD_TO_SCOIN */
	public static final IconEntry SPS_GOLD_TO_SCOIN = new IconEntry("sprites/items/specific/place_holder.png", new int[]{209, 51, 14, 11});
	/** SPS_PH_BADGE_ALT */
	public static final IconEntry SPS_PH_BADGE_ALT = new IconEntry("sprites/items/specific/place_holder.png", new int[]{243, 52, 10, 9});
}
