# gen-atlas-dict.ps1
#   Generate pd/atlas dictionaries from tools/atlas-meta/**/_atlas.json.
#   One dictionary class per atlas metadata file; the atlas metadata stays the single source of truth.
#
# Usage:
#   .\tools\gen-atlas-dict.ps1                 # write dictionaries into core/src/java/pd/atlas
#   .\tools\gen-atlas-dict.ps1 -Check          # regenerate into a temp dir and diff against the committed ones
#
# Notes:
#   - This script is intentionally ASCII-only; generated sources carry an ASCII header, so no encoding traps.
#   - Entry identifiers come from the metadata "file" field (semantic names for items,
#     grid names such as tile_034 for tiles), uppercased with non-alphanumerics folded to '_'.
#   - The atlas path written into the dictionary is relative to the assets root
#     (the metadata stores it relative to the repository root).

param(
	[string]$MetaRoot     = 'tools/atlas-meta',
	[string]$OutRoot      = 'core/src/java/pd/atlas',
	[string]$AssetsPrefix = 'core/src/assets/',
	[switch]$Check
)

$ErrorActionPreference = 'Stop'
$utf8 = New-Object Text.UTF8Encoding($false)
$repoRoot = (Get-Location).Path

function ConvertTo-Camel([string]$name) {
	$parts = [regex]::Split($name, '[^A-Za-z0-9]+') | Where-Object { $_ -ne '' }
	$s = ''
	foreach ($p in $parts) {
		if ($p.Length -eq 0) { continue }
		$s += $p.Substring(0, 1).ToUpperInvariant() + $p.Substring(1)
	}
	if ($s -eq '') { $s = 'Atlas' }
	if ($s -match '^[0-9]') { $s = 'N' + $s }
	return $s
}

function ConvertTo-Identifier([string]$name) {
	$s = [regex]::Replace($name, '[^A-Za-z0-9]+', '_').Trim('_').ToUpperInvariant()
	if ($s -eq '') { $s = 'ENTRY' }
	if ($s -match '^[0-9]') { $s = 'N' + $s }
	return $s
}

function Resolve-Dir([string]$path) {
	if ([IO.Path]::IsPathRooted($path)) { return $path }
	return (Join-Path $repoRoot $path)
}

# real output (what the repository expects), and the actual target for this run
$realOutFull = Resolve-Dir $OutRoot
$targetOut   = if ($Check) { Join-Path $env:TEMP ('spx-atlas-check-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)) } else { $realOutFull }
if (-not (Test-Path $targetOut)) { New-Item -ItemType Directory -Force -Path $targetOut | Out-Null }

$metaRootFull = Resolve-Dir $MetaRoot
$metas = @(Get-ChildItem -Recurse -File -Filter '_atlas.json' $metaRootFull | Sort-Object FullName)
if ($metas.Count -eq 0) { throw "no _atlas.json found under $MetaRoot" }

$written = 0
foreach ($meta in $metas) {
	$rel  = $meta.FullName.Substring($metaRootFull.Length + 1)
	$dirs = @([regex]::Split($rel, '[\\/]') | Where-Object { $_ -ne '_atlas.json' -and $_ -ne '' })
	if ($dirs.Count -eq 0) { continue }

	$json = Get-Content -Raw -LiteralPath $meta.FullName | ConvertFrom-Json
	$atlasRel = ([string]$json.atlas).Replace($AssetsPrefix, '').Replace('\', '/')
	if ($atlasRel -eq '') { throw "empty atlas path in $rel" }

	$pkgName   = 'pd.atlas.' + $dirs[0]
	# Nested atlas metadata (e.g. items/consum/food) must yield unique class names:
	# join from the second path segment on, so `environment/tiles_sewers` stays TilesSewersDict
	# while `items/consum/food` becomes ConsumFoodDict.
	$nameParts = if ($dirs.Count -gt 1) { @($dirs[1..($dirs.Count - 1)]) } else { @($dirs[-1]) }
	$classBase = ($nameParts | ForEach-Object { ConvertTo-Camel $_ }) -join ''
	$className = $classBase + 'Dict'
	$pkgDir    = Join-Path $targetOut $dirs[0]
	if (-not (Test-Path $pkgDir)) { New-Item -ItemType Directory -Force -Path $pkgDir | Out-Null }

	$sb = New-Object Text.StringBuilder
	[void]$sb.AppendLine('package ' + $pkgName + ';')
	[void]$sb.AppendLine('')
	[void]$sb.AppendLine('import pd.atlas.IconEntry;')
	[void]$sb.AppendLine('')
	[void]$sb.AppendLine('/**')
	[void]$sb.AppendLine(' * Icon dictionary generated by tools/gen-atlas-dict.ps1 from')
	[void]$sb.AppendLine(' * tools/atlas-meta/' + ($dirs -join '/') + '/_atlas.json - do not edit by hand.')
	[void]$sb.AppendLine(' *')
	[void]$sb.AppendLine(' * atlas: ' + $atlasRel)
	[void]$sb.AppendLine(' */')
	[void]$sb.AppendLine('public final class ' + $className + ' {')
	[void]$sb.AppendLine('')
	[void]$sb.AppendLine('	private ' + $className + '() { }')
	[void]$sb.AppendLine('')

	$used = @{}
	$count = 0
	foreach ($e in $json.entries) {
		$file = [string]$e.file
		if ($file -eq '') { continue }
		$ident = ConvertTo-Identifier $file
		if ($used.ContainsKey($ident)) {
			$used[$ident]++
			$ident = $ident + '_' + $used[$ident]
		} else {
			$used[$ident] = 1
		}

		$rects = New-Object System.Collections.Generic.List[string]
		foreach ($f in $e.frames) {
			$rects.Add([string][int]$f.x); $rects.Add([string][int]$f.y)
			$rects.Add([string][int]$f.w); $rects.Add([string][int]$f.h)
		}
		if ($rects.Count -eq 0) { continue }

		[void]$sb.AppendLine('	/** ' + $file + ' */')
		[void]$sb.AppendLine('	public static final IconEntry ' + $ident + ' = new IconEntry(' +
			'"' + $atlasRel + '", new int[]{' + ($rects -join ', ') + '});')
		$alias = [string]$e.alias
		if ($alias -ne '') {
			$aliasIdent = ConvertTo-Identifier $alias
			[void]$sb.AppendLine('	/** legacy alias for ' + $ident + ' */')
			[void]$sb.AppendLine('	public static final IconEntry ' + $aliasIdent + ' = ' + $ident + ';')
		}
		$count++
	}

	[void]$sb.AppendLine('}')
	$target = Join-Path $pkgDir ($className + '.java')
	[IO.File]::WriteAllText($target, $sb.ToString(), $utf8)
	$written++
	if (-not $Check) {
		Write-Host ("  {0,-46} {1,5} entries  ->  {2}" -f $rel, $count, $target.Replace($repoRoot + '\', ''))
	}
}

if ($Check) {
	$mine = @(Get-ChildItem -Recurse -File -Filter *Dict.java $targetOut | ForEach-Object {
		$_.FullName.Substring($targetOut.Length) + '|' + (Get-FileHash $_.FullName -Algorithm SHA256).Hash
	})
	$theirs = @(Get-ChildItem -Recurse -File -Filter *Dict.java $realOutFull | ForEach-Object {
		$_.FullName.Substring($realOutFull.Length) + '|' + (Get-FileHash $_.FullName -Algorithm SHA256).Hash
	})
	$diff = @(Compare-Object $mine $theirs)
	Remove-Item -Recurse -Force $targetOut
	if ($diff.Count -gt 0) {
		Write-Host "dictionaries out of date (diff count: $($diff.Count)):" -ForegroundColor Red
		$diff | Select-Object -First 20 | ForEach-Object { Write-Host ("  {0} {1}" -f $_.SideIndicator, $_.InputObject) }
		Write-Host 're-run tools/gen-atlas-dict.ps1'
		exit 1
	}
	Write-Host 'verifyIconDict: dictionaries match tools/atlas-meta'
	exit 0
}

Write-Host ("gen-atlas-dict: {0} dictionaries written to {1}" -f $written, $OutRoot)
