package pd.atlas.effects;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/effects/banners/_atlas.json - do not edit by hand.
 *
 * atlas: effects/banners.png
 */
public final class BannersDict {

	private BannersDict() { }

}
